# Generated by Django 3.1.5 on 2022-01-10 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bookingdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('totalpeople', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'bookingdetails',
            },
        ),
    ]
