# Generated by Django 3.1.5 on 2022-02-05 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restapp', '0002_contactdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='restdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('special', models.CharField(max_length=60)),
                ('opentime', models.TimeField()),
                ('closetime', models.TimeField()),
            ],
            options={
                'db_table': 'restdetails',
            },
        ),
        migrations.AddField(
            model_name='bookingdetails',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='auth.user'),
            preserve_default=False,
        ),
    ]
